spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    tomcat:
      driver-class-name: com.mysql.jdbc.Drive
      url: jdbc:mysql://localhost:3306/student?useUnicode=true&amp;characterEncoding=utf-8
      username: root
      password: 123456